# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='profileId',
            field=models.CharField(
                max_length=40, primary_key=True, serialize=False),
        ),
    ]
