# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160617_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessionId',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
