# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160617_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileId',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
