# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160618_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileId',
            field=models.CharField(default='', max_length=40),
        ),
    ]
