# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160620_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batchName',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='branchName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='collegeId',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='sectionName',
            field=models.CharField(default='', max_length=5),
        ),
    ]
