# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_gcmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gcmId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
